### ISSUE TITLE
New in Town Re-Certification for Quality-Datapacker Role

### ISSUE THREAD

**Issue by kanokarob** [mc-datapacks/review-tracker#10]
Project Page: https://www.planetminecraft.com/data-pack/new-in-town-a-settler-s-experience-data-pack/

**Comment by oOBoomberOo** [comment]
@kanokarob 
You also need to include/refer uninstallation instruction inside the project page as well besides including it in the readme.

**Comment by kanokarob** [comment]
Project page updated.

**Comment by oOBoomberOo** [comment]
All good to go 👍 

- Certified Datapack ✔️ 
- Stamp of Quality ✔️
