### ISSUE TITLE
BlingTreesReload 

### ISSUE THREAD

**Issue by playbabe** [mc-datapacks/review-tracker#13]
Project Page: https://www.planetminecraft.com/data-pack/blingtrees-reload-tree-actually-falling-when-cut/
download ling: https://drive.google.com/drive/u/0/folders/1soIUdaJIWz6N0owyv4r4jGdHcbaYVXql

**Comment by EstEarth202** [comment]
@playbabe 

- Certified Compatibility :x: 
- Stamp of Quality :x: 

### Global ignore

- [x] คำสั่ง `kill @e` ที่เหมือนกับคำสั่งตามข้างล่างนี้ไม่มี `!global.ignore` + `!global.ignore.kill` นะ ซึ่งไม่ได้มีแค่ไฟล์เดียว

```
data\playbabe\functions\btr\loot\give_loot\acacia_leaves.mcfunction

kill @e[type=item,limit=1,sort=nearest,nbt={Item:{id:"minecraft:acacia_leaves"}}]
```

### Uninstallation

- [ ] บอกวิธีถอนการติดตั้งที่หน้าเว็บ Planetminecraft ด้วยเหมือนกัน

### เพิ่มเติม

สำหรับ Fake player scoreboard ไม่จำเป็นต้องมี namespace ก็ได้ เช่น pbbs#360 ก็คืออยากตั้งชื่ออะไรก็ได้ตามใจเลย

จำพวกเลขรหัส \u0020 สามารถก๊อปปี้เอาตัวจริงมาใส่ในงานได้เลยโดยตรง ห้ามทำใน Notepad++ ถ้าจำไม่ผิดเพราะมันจะมองไม่เห็นเป็นแค่กล่องสี่เหลี่ยม

**Comment by playbabe** [comment]
Update แล้ว ลิ้งเดิม
แก้ไข Global ignore และ Uninstallation ที่หน้าเว็บ Planetminecraft
* Fake player scoreboard namespace ตั้งไว้เท่ดี ถถถถถ
** \u0020 ใช้ unicode กันงง

**Comment by EstEarth202** [comment]
- Certified Compatibility:heavy_check_mark:
- Stamp of Quality :two_hearts:
- Datapack reviewer @EstEarth202. :thumbsup:
