### ISSUE TITLE
Sandwiches Galore

### ISSUE THREAD

**Issue by Ellivers** [mc-datapacks/review-tracker#15]
Project Page: <https://www.planetminecraft.com/data-pack/sandwiches-galore/>

**Comment by oOBoomberOo** [comment]
@Ellivers 
- Certified Compatibility ❌ 
- Stamp of Quality ❌ 

## Global Ignoring Tag

There are many mistake with the global ignoring tag convention but easily fixable:
1. Missing `global.ignore` tag for `@e`
    - [ ] [sandwiches_galore:item_tick](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/item_tick.mcfunction#L7)
    - [ ] [sandwiches_galore:break/bowl](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/break/bowl.mcfunction#L4)
    - [ ] [sandwiches_galore:break/crafter](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/break/crafter.mcfunction#L6)
    - [ ] [sandwiches_galore:break/grinder](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/break/grinder.mcfunction#L8)
    - [ ] [sandwiches_galore:break/oven](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/break/oven.mcfunction#L8)
    - [ ] [sandwiches_galore:break/sandwich_table](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/break/sandwich_table.mcfunction#L6)
    - [ ] [sandwiches_galore:crops/buckwheat/bonemeal](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/crops/buckwheat/bonemeal.mcfunction#L6)
    - [ ] [sandwiches_galore:crops/corn/bonemeal](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/crops/corn/bonemeal.mcfunction#L6)
    - [ ] [sandwiches_galore:large_bowl/dough/buckwheat](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/large_bowl/dough/buckwheat.mcfunction#L3)
    - [ ] [sandwiches_galore:large_bowl/dough/nether_sprout](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/large_bowl/dough/nether_sprout.mcfunction#L3)
    - [ ] [sandwiches_galore:large_bowl/dough/wheat](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/large_bowl/dough/wheat.mcfunction#L3)
    - [ ] [sandwiches_galore:machines/crafter/output/corn_seeds](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/corn_seeds.mcfunction#L7-L8)
    - [ ] [sandwiches_galore:machines/crafter/output/corn_seeds2](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/corn_seeds2.mcfunction#L4-L5)
    - [ ] [sandwiches_galore:machines/crafter/output/cutting_board](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/cutting_board.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/grinder](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/grinder.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/knife](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/knife.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/large_bowl](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/large_bowl.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/oven](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/oven.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/sandwich_table](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/sandwich_table.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/large_bowl](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/large_bowl.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/whisk](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/whisk.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/sandwich_table/output/buckwheat_base](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/buckwheat_base.mcfunction#L3-L4)
    - [ ] [sandwiches_galore:machines/sandwich_table/output/corn_base](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/corn_base.mcfunction#L3-L4)
    - [ ] [sandwiches_galore:machines/sandwich_table/output/nether_sprout_base](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/nether_sprout_base.mcfunction#L3-L4)
    - [ ] [sandwiches_galore:machines/sandwich_table/output/sandwich](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/sandwich.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/sandwich_table/output/wheat_base](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/wheat_base.mcfunction#L3-L4)
    - [ ] [sandwiches_galore:place/buckwheat/place](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/place/buckwheat/place.mcfunction#L2)
    - [ ] [sandwiches_galore:place/corn/place](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/place/corn/place.mcfunction#L2)
    - [ ] [sandwiches_galore:place/crafter/make](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/place/crafter/make.mcfunction#L1)

2. `global.ignore` tag in player selector is **not** allowed
    - [ ] [path](link)
    - [ ] [path](link)
    - [ ] [path](link)
    - [ ] [path](link)
    - [ ] [path](link)
    - [ ] [path](link)
    - [ ] [path](link)
    - [ ] [path](link)
    - [ ] [path](link)
    - [ ] [path](link)
    - [ ] [path](link)

**Comment by oOBoomberOo** [comment]
@Ellivers 
- Certified Compatibility ❌ 
- Stamp of Quality ❌ 

## Global Ignoring Tag

There are many mistakes with the global ignoring tag convention but easily fixable:
1. Missing `global.ignore` tag for `@e`
    - [ ] [sandwiches_galore:item_tick](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/item_tick.mcfunction#L7)
    - [ ] [sandwiches_galore:break/bowl](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/break/bowl.mcfunction#L4)
    - [ ] [sandwiches_galore:break/crafter](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/break/crafter.mcfunction#L6)
    - [ ] [sandwiches_galore:break/grinder](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/break/grinder.mcfunction#L8)
    - [ ] [sandwiches_galore:break/oven](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/break/oven.mcfunction#L8)
    - [ ] [sandwiches_galore:break/sandwich_table](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/break/sandwich_table.mcfunction#L6)
    - [ ] [sandwiches_galore:crops/buckwheat/bonemeal](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/crops/buckwheat/bonemeal.mcfunction#L6)
    - [ ] [sandwiches_galore:crops/corn/bonemeal](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/crops/corn/bonemeal.mcfunction#L6)
    - [ ] [sandwiches_galore:large_bowl/dough/buckwheat](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/large_bowl/dough/buckwheat.mcfunction#L3)
    - [ ] [sandwiches_galore:large_bowl/dough/nether_sprout](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/large_bowl/dough/nether_sprout.mcfunction#L3)
    - [ ] [sandwiches_galore:large_bowl/dough/wheat](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/large_bowl/dough/wheat.mcfunction#L3)
    - [ ] [sandwiches_galore:machines/crafter/output/corn_seeds](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/corn_seeds.mcfunction#L7-L8)
    - [ ] [sandwiches_galore:machines/crafter/output/corn_seeds2](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/corn_seeds2.mcfunction#L4-L5)
    - [ ] [sandwiches_galore:machines/crafter/output/cutting_board](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/cutting_board.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/grinder](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/grinder.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/knife](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/knife.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/large_bowl](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/large_bowl.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/oven](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/oven.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/sandwich_table](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/sandwich_table.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/large_bowl](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/large_bowl.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/crafter/output/whisk](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output/whisk.mcfunction#L2-L3)
    - [ ] [sandwiches_galore:machines/sandwich_table/output/buckwheat_base](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/buckwheat_base.mcfunction#L3-L4)
    - [ ] [sandwiches_galore:machines/sandwich_table/output/corn_base](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/corn_base.mcfunction#L3-L4)
    - [ ] [sandwiches_galore:machines/sandwich_table/output/nether_sprout_base](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/nether_sprout_base.mcfunction#L3-L4)
    - [ ] [sandwiches_galore:machines/sandwich_table/output/sandwich](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/sandwich.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/sandwich_table/output/wheat_base](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/wheat_base.mcfunction#L3-L4)
    - [ ] [sandwiches_galore:place/buckwheat/place](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/place/buckwheat/place.mcfunction#L2)
    - [ ] [sandwiches_galore:place/corn/place](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/place/corn/place.mcfunction#L2)
    - [ ] [sandwiches_galore:place/crafter/make](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/place/crafter/make.mcfunction#L1)

2. `global.ignore` tag in player selector is **not** allowed
    - [ ] [sandwiches_galore:tick](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/tick.mcfunction#L15)
    - [ ] [sandwiches_galore:bowl/fill_bottle](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/bowl/fill_bottle.mcfunction#L2)
    - [ ] [sandwiches_galore:bowl/whisk.give](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/bowl/whisk.give.mcfunction#L3)
    - [ ] [sandwiches_galore:bowl/whisk](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/bowl/whisk.mcfunction#L14)
    - [ ] [sandwiches_galore:bowl/add/water.add](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/bowl/add/water.add.mcfunction#L6)
    - [ ] [sandwiches_galore:bowl/add/water.poof](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/bowl/add/water.poof.mcfunction#L5)
    - [ ] [sandwiches_galore:bowl/crops/corn/give_back_item](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/crops/corn/give_back_item.mcfunction#L6)
    - [ ] [sandwiches_galore:cutting_board/items/cut_bread2](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/cutting_board/items/cut_bread2.mcfunction#L8)
    - [ ] [sandwiches_galore:cutting_board/knife.give](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/cutting_board/items/knife.give.mcfunction#L3)
    - [ ] [sandwiches_galore:large_bowl/fill_bucket](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/large_bowl/fill_bucket.mcfunction#L2)
    - [ ] [sandwiches_galore:large_bowl/whisk.give](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/large_bowl/whisk.give.mcfunction#L3)
    - [ ] [sandwiches_galore:large_bowl/whisk](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/large_bowl/whisk.mcfunction#L15)
    - [ ] [sandwiches_galore:large_bowl/add/water.add](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/large_bowl/add/water.add.mcfunction#L6)
    - [ ] [sandwiches_galore:large_bowl/add/water.poof](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/large_bowl/add/water.poof.mcfunction#L5)
    - [ ] [sandwiches_galore:machines/crafter/output.full](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output.full.mcfunction#L4-L11)
    - [ ] [sandwiches_galore:machines/crafter/output](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output.mcfunction#L1-L2)
    - [ ] [sandwiches_galore:machines/crafter/output.once](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/crafter/output.once.mcfunction#L4-L12)
    - [ ] [sandwiches_galore:machines/reject_slots/0](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/0.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/1](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/1.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/2](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/2.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/3](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/3.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/4](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/4.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/5](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/5.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/6](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/6.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/7](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/7.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/8](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/8.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/9](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/9.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/10](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/10.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/11_oven](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/11_oven.mcfunction#L3)
    - [ ] [sandwiches_galore:machines/reject_slots/11](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/11.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/12](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/12.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/13_grinder](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/13_grinder.mcfunction#L3)
    - [ ] [sandwiches_galore:machines/reject_slots/13_oven](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/13.mcfunction#L3)
    - [ ] [sandwiches_galore:machines/reject_slots/13](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/13.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/14](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/14.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/15](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/15.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/16_sandwich_table](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/16_sandwich_table.mcfunction#L1)
    - [ ] [sandwiches_galore:machines/reject_slots/16](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/16.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/17](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/17.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/18](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/18.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/19](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/19.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/20](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/20.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/21](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/21.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/22](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/22.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/23](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/23.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/24](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/24.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/25](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/25.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/reject_slots/26](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/reject_slots/26.mcfunction#L2)
    - [ ] [sandwiches_galore:machines/sandwich_table/output/output (1)](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/output.mcfunction#L9-L13) and [sandwiches_galore:machines/sandwich_table/output/output (2)](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/machines/sandwich_table/output/output.mcfunction#L2)
    - [ ] [sandwiches_galore:place/buckwheat/place](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/place/buckwheat/place.mcfunction#L4)
    - [ ] [sandwiches_galore:place/corn/place](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/place/corn/place.mcfunction#L4)
    - [ ] [sandwiches_galore:place/cutting_board/rot](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/place/cutting_board/rot.mcfunction#L1)
    - [ ] [sandwiches_galore:place/oven/rot](https://github.com/Ellivers/Sandwiches-Galore/blob/e4b2798516360a5f267e95b87634a66f27a43f8c/Datapack/data/sandwiches_galore/functions/place/oven/rot.mcfunction#L1)

## Common Trait Convention

While not enforced, it is recommended that you adopt the custom trait convention into your custom item.

**Comment by Ellivers** [comment]
I'll close this for now. Will probably fix the convention issues when I update it one day.
