### ISSUE TITLE
Improved Apiculture v0.1.0

### ISSUE THREAD

**Issue by TheWii** [mc-datapacks/review-tracker#16]
Project Page: https://github.com/TheWii/improved-apiculture/releases/v0.1.0

**Comment by ghost** [comment]
Certified Compatibility ❌
Stamp of Quality ❌
Great and creative ✔️

Here's the review:

❌= didn't follow  ✔️= followed
Tier 3 Conventions:

- ✔️Custom Model ID
- ❌Global Ignoring Tag
 _improved-apiculture-datapack-v0-1-0\data\thewii\functions\apiculture\player\placed\dispenser\grid\_z.mcfunction_
 `unless entity @e[type=#thewii:apiculture/custom_block,limit=1,distance=..0.5]`
 This selector includes all the entities of certain types, also if they have the global.ignore tag.
 _improved-apiculture-datapack-v0-1-0\data\thewii\functions\apiculture\player\placed\dispenser\raycast.mcfunction_
 Same thing here.
- ✔️Yellow Shulker Box
- ✔️Namespace

Tier 2 Conventions:

- ✔️Common Traits

Tier 1 Conventions:

- ✔️Datapack Advancement
- ❌Uninstall
 You should also specify in the datapack description how people can uninstall the datapack.


I really like this datapack. Vanilla style and really really nice. Mojang should assume you.
Just one thing: too difficult structure.

**Comment by TheWii** [comment]
### Tier 3 Conventions:

>❌Global Ignoring Tag
improved-apiculture-datapack-v0-1-0\data\thewii\functions\apiculture\player\placed\dispenser\grid_z.mcfunction
unless entity @e[type=#thewii:apiculture/custom_block,limit=1,distance=..0.5]
This selector includes all the entities of certain types, also if they have the global.ignore tag.
improved-apiculture-datapack-v0-1-0\data\thewii\functions\apiculture\player\placed\dispenser\raycast.mcfunction
Same thing here.

This is intended for what it wants to do. It checks for dispensers and summon an area effect cloud on them(it still isn't used for anything, but in the future it will help me to keep track of dispensers shearing beehives). The full line is:
```
execute positioned ~ ~ ~ if block ~ ~ ~ minecraft:dispenser unless entity @e[type=#thewii:apiculture/custom_block,limit=1,distance=..0.5] run function thewii:apiculture/block/dispenser/place
```
We could read this as **"If this block is a dispenser and there is no armor stand or area effect cloud on it, we should continue"**

Dispensers are commonly used as Crafting Tables, so what I'm doing here is **avoiding to summon my AEC in a dispenser that already has an entity(meaning it could be a custom block)**, if I set `tag=!global.ignore` the `unless entity` won't detect such entities(which probably have the tag `global.ignore`).

### Tier 1 Conventions:

>❌Uninstall
You should also specify in the datapack description how people can uninstall the datapack.

I didn't explain it directly, but there are some links that redirect to my wiki where I explain about it.

<img src="https://i.imgur.com/qzgASZ8.png" width="480">
<img src= "https://i.imgur.com/1CpTtE4.png", width="480">

**Comment by ghost** [comment]
Yes, it makes sense.

Certified Compatibility ✔️
Stamp of Quality ✔️
Great and creative ✔️
