### ISSUE TITLE
mcEXP Reborn (re-cert for SoQ)

### ISSUE THREAD

**Issue by eatYourHashs** [mc-datapacks/review-tracker#17]
Project Page: https://www.planetminecraft.com/data-pack/mcexp-reborn-rpg-progression-rebirthed/
This is a re-submission for the Stamp of Quality. The only changes are additional skills added over the past few updates (which I doubt would cause issues) and the changes made to receive the Stamp of Quality.

**Comment by EstEarth202** [comment]
@eatYourHashs 

- Certified Compatibility ❌(Roll-back Review)
- Stamp of Quality ✅

## Global Ignoring Tag

There are many mistakes with the global ignoring tag convention but easily fixable:

1. `global.ignore` tag in player selector is not allowed & `tellraw` not required  `global.ignore & gui`

      - [x] mcfunction in `mcexp2\functions\levelup` folder.
      - [x] mcfunction in `mcexp2\functions\prestige` folder
      - [x] mcfunction in `mcexp2\functions\skill_points` folder
      - [x] mcfunction in `mcexp2\functions\skillbook\buy` folder
      - [x] mcfunction in `mcexp2\functions\skillbook` folder
      - [x] `mcexp2\functions\common_tick` `execute as @a[tag=!global.ignore]
      - [x] `mcexp2\functions\uninstall`
`
2. `playsound` & `particle` not required  `global.ignore & gui`
      - [x] mcfunction in `mcexp2\functions\skills` folder

**Comment by eatYourHashs** [comment]
I have fixed the issues above; the new release is uploaded to the same PMC link.

**Comment by EstEarth202** [comment]
## From again review, there were few issues.

      

- [x] `mcexp2\functions\player_tick` -> `kill @e[type=item,distance=..6.kill,limit=1,nbt={Item:{id:"minecraft:ancient_debris",Count:1b}}]` You use find and replace, which makes both globals deleted.

- [x] From checking the order of the command function
The `title` command is required. `!global.ignore.gui` but easily fixable by putting it at `execute as @a[tag=!global.ignore.gui] at @s run function mcexp2:player_tick` in `mcexp2\functions\common_tick`

### And that's all

**Comment by eatYourHashs** [comment]
I have fixed the above; the new release is once again uploaded to the same PMC link.

**Comment by EstEarth202** [comment]
- Certified Compatibility :heavy_check_mark:
- Stamp of Quality :heavy_check_mark:
- No Final Comment
