### ISSUE TITLE
More Mobs (Snapshot 4A)

### ISSUE THREAD

**Issue by iNkoR-the-2nd** [mc-datapacks/review-tracker#22]
[UPCOMING RELEASE] Project Page: https://www.planetminecraft.com/data-pack/more-mobs-snapshot-3c/
Whoever is assigned, I want to send them the archive via Discord DMs

**Comment by ghost** [comment]
❌Certified Datapack
❌Stamp of Quality
Here where you didn't follow conventions.
# Tier 3 Conventions (You need to follow them to get certified datapack banner)
### Global Ignoring Tag Convention:
Convention changed, maybe not in the right way, but they changed.
You don't need anymore to use tag=!global.ignore in @a selectors.
You also don't need to use tag=!global.ignore.gui for /tellraw, /playsound and /particle
**Remember to check for new conventions here: [>Convention Site<](https://mc-datapacks.github.io/en/conventions/)**
But you need, instead, tag=!global.ignore.gui for /title commands(you didn't put them in all play.mcfunction files).

# Tier 2,1 Conventions (You don't need to follow them, but you should if you want the Stamp of Quality)
### Common Traits Convention:
You just didn't follow it.

### Datapack Advancement:
-root.json should have this content:
```
{
    "display": {
        "title": "Installed Datapacks",
        "description": "",
        "icon": {
            "item": "minecraft:knowledge_book"
        },
        "background": "minecraft:textures/block/gray_concrete.png",
        "show_toast": false,
        "announce_to_chat": false
    },
    "criteria": {
        "trigger": {
            "trigger": "minecraft:tick"
        }
    }
}
```
-data\global\advancements\imm.json should not be in that directory.
Citing conventions:
> You can create this advancement anywhere, as long as you don't pollute /data/global/advancements/folder.

Also, don't keep your old commands as comments.

**Comment by ghost** [comment]
Still waiting for your reply in here

**Comment by iNkoR-the-2nd** [comment]
I sent the new file over Discord.

**Comment by ghost** [comment]
## More Mobs (Snapshot 4A)
✔️Certified Datapack
❌Stamp of Quality

You can now place [this banner](https://i.imgur.com/4Z0ioH5.png) on descriptions, sites and wikies about the datapack.

You followed all Tier 3 Conventions.
But you didn't follow, instead, Uninstall and Common Traits Conventions (I said it last time and you didn't change anything, so I suppose you don't want to apply it, and it's not a problem), so you can't get the Stamp of Quality.

### Suggestions:
- Claims again your Custom Model Data ID logging in this site: https://mcdatapacks.vercel.app
- Don't keep your old commands as comments, except if they can really be useful (they are a problem reviewing and generally studying the pack).
- Don't use more than 1 execute as @e in all the datapack. Use only one
`execute as @e[type=#typesofallentitiesmydatapackwantstoexecutecommands] run function <a function all entities I want run>` 
and than in that function check first the entity and only after you did it you take the coordinates with at @s (except if you also need to check blocks or things about locations and distance, in that case you can use at @s first).
- Don't use at @s to check things about the entity and don't use at @s as @s. In this way you go to ask for the entity position and then check if the entity will execute commands, creating useless lag. Someone is teaching me base things about optimization inside datapacks.

Maybe you could not like my suggestions, maybe I said something wrong. But I hope you check what I said and, maybe, apply them!
