### ISSUE TITLE
Fireworks+ Datapack

### ISSUE THREAD

**Issue by ghost** [mc-datapacks/review-tracker#23]
Project Page: https://www.planetminecraft.com/data-pack/fireworks-more-types-of-fireworks/

**Comment by EstEarth202** [comment]
@UltroGhast 

- Certified Compatibility ✔️
- Stamp of Quality ❌ [ If you don't want it, tell me. ]
- Final comment after closed verified.

### Datapack Uninstallation missing

**Comment by ghost** [comment]
Uninstall function isn't needed, since all the scoreboards used in that datapack are scoreboards I use in most of my datapacks

**Comment by EstEarth202** [comment]
@UltroGhast 

- Certified Compatibility ✔️
- Stamp of Quality 💕
- Good pack :thumbsup: 

### Do not forget to tell to the user why.
