### ISSUE TITLE
Beehive / Bee nest tooltips

### ISSUE THREAD

**Issue by mainrs** [mc-datapacks/review-tracker#27]
Project Page: https://github.com/vanilla-friendly-datapacks/beehive-tooltips

**Comment by EstEarth202** [comment]
@SirWindfield 

- Certified Compatibility ❌
- Stamp of Quality ❌
- Final comment after closed verified.

## Certified Compatibility part

### Global Ignoring tag

`zerotask\functions\beehive_tooltips\tick.mcfunction` `tag=!global.ignore` missing

## Stamp of Quality part
If you just want Certified Compatibility You can skip this part.

### Datapack Uninstallation missing

**Comment by mainrs** [comment]
Problems have been fixed by pushing a new commit to the repo. Thanks for taking your time to review the pack!

**Comment by EstEarth202** [comment]
- Certified Compatibility:heavy_check_mark:
- Stamp of Quality :two_hearts:
- And LMAO Datapack reviewer @EstEarth202. :thumbsup:
