### ISSUE TITLE
Pocket Shulker

### ISSUE THREAD

**Issue by oOBoomberOo** [mc-datapacks/review-tracker#29]
Project Page: https://www.planetminecraft.com/data-pack/pocket-shulker/

**Comment by EstEarth202** [comment]
- Certified Compatibility:heavy_check_mark:
- Stamp of Quality :two_hearts:
- ### And **Great pack, This is one of the best sample packs to guideline about file directories structure, optimization & namespace. LMAO Datapack reviewer @EstEarth202. :thumbsup: **

**Comment by oOBoomberOo** [comment]
Thank you for the review!
