### ISSUE TITLE
Death Control

### ISSUE THREAD

**Issue by Armoured-Monkey** [mc-datapacks/review-tracker#35]
Project Page: https://www.planetminecraft.com/data-pack/death-control/

**Comment by ghost** [comment]
✔️Certified Datapack
❌Stamp of Quality

**global\advancements\deathcontrol.json** should be somewhere else.
> You can create this advancement anywhere, as long as you don't pollute /data/global/advancements/folder.

It's hard not to follow conventions with a small datapack like this. And easy to review.
Let me know if you also want the "Stamp of Quality" or if the Certified Datapack banner is enough.

**Comment by Armoured-Monkey** [comment]
Thanks, I've updated it and made that change.

**Comment by ghost** [comment]
✔️Certified Datapack
✔️"Stamp of Quality"

You can now use [THIS BANNER](https://i.imgur.com/ltLPoQp.png) in the datapack description, wiki, download pages.
