### ISSUE TITLE
Review for Asphodel Meadows v2.1 

### ISSUE THREAD

**Issue by AidenGyory** [mc-datapacks/review-tracker#38]
Project Page: https://www.planetminecraft.com/data-pack/asphodel-meadows-v2-0-custom-dimension-for-1-16/

**Comment by ghost** [comment]
❌Certified Datapack
❌Stamp of Quality
(If the stamp of quality indicated quality, I would have given it to you with my eyes closed.)
Really nice Datapack, hope you will fix the compatibility problems.
# Need to follow Tier 3 Conventions if you want the Compatibility Certification.
### Global Ignoring Tag Convention
_asphodel-meadows-v2-1\data\asphodel\functions\player_tick.mcfunction_
`as @e[type=minecraft:zombie,distance=..128] and as @e[type=minecraft:ghast,distance=..128,tag=!AM.IsBoss]`
_asphodel-meadows-v2-1\data\asphodel\functions\accessories\axe\loop.mcfunction_
`execute as @e[sort=nearest,limit=1,distance=..10,tag=!am_Checked,type=item,nbt={Item:{id:"minecraft:oak_log"}}]` etc.
_asphodel-meadows-v2-1\data\asphodel\functions\global_tick.mcfunction_
`execute as @e[type=experience_bottle,tag=!am_Checked] at @s run function asphodel:essence/check`
`execute as @e[type=firework_rocket,tag=!am_Checked] run function asphodel:custom_blocks/block_check`
`execute as @e[type=item,tag=!am_Checked] run function asphodel:check_item`
_asphodel-meadows-v2-1\data\asphodel\functions\accessories\axe\main.mcfunction_
`execute as @e[sort=nearest,limit=1,distance=..10,tag=!am_Checked,type=item,nbt={Item:{id:"minecraft:oak_log"}}]` etc.
_asphodel-meadows-v2-1\data\asphodel\functions\custom_portal\portal.mcfunction_
`as @e[type=#asphodel:can_tp,tag=!p1_teleported]`
_asphodel-meadows-v2-1\data\asphodel\functions\accessories\magic_mirror\repair.mcfunction_
`tag @e[type=item,limit=1,sort=nearest,nbt={Item:{id:"minecraft:diamond"}}]`
**You shouldn't include entities (except for players) with global.ignore tag in any selector**
**All /title commands show text to players with global.ignore.gui tag, they should not**
_asphodel-meadows-v2-1\data\asphodel\functions\accessories\hoarding_amulet\drop_items.mcfunction_
`kill @e[type=item,nbt={Item:{id:"minecraft:barrier"}}]`
_asphodel-meadows-v2-1\data\asphodel\functions\custom_blocks\infernal_machine\drop.mcfunction_
`kill @e[distance=..1,type=minecraft:item,nbt={Item:{id:"minecraft:trapped_chest"}}]`
_asphodel-meadows-v2-1\data\asphodel\functions\custom_blocks\onyx\drop_vase.mcfunction_
`kill @e[distance=..1,type=minecraft:item,nbt={Item:{id:"minecraft:trapped_chest"}}]`
**You must not kill entities with global.ignore or global.ignore.kill tag.**
### Namespace Convention
**All the tags must have the namespace. All.**
Also, /trigger scores are allowed not to have the namespace
### Custom Model ID Convention
**Your Custom Model ID results 113, while the datapack uses 11XXXX and 141XXXX Custom Model Data formats.**
You should only use 113+4 numbers for your Custom Model Data tags.
You can only own one ID.
## Fix the next things if you also want the Stamp of Quality
### Datapack Advancement Convention
_asphodel-meadows-v2-1\data\global\advancements\asphodel\asphodel.json_ should not be there.
quoting conventions:
> as long as you don't pollute /data/global/advancements/folder

Reply here when you update the datapack and fix everything.

**Comment by AidenGyory** [comment]
Have made all the changes recommended - Please let me know what you think!

**Comment by AidenGyory** [comment]
> ❌Certified Datapack
> ❌Stamp of Quality
> (If the stamp of quality indicated quality, I would have given it to you with my eyes closed.)
> Really nice Datapack, hope you will fix the compatibility problems.
> 
> # Need to follow Tier 3 Conventions if you want the Compatibility Certification.
> ### Global Ignoring Tag Convention
> _asphodel-meadows-v2-1\data\asphodel\functions\player_tick.mcfunction_
> `as @e[type=minecraft:zombie,distance=..128] and as @e[type=minecraft:ghast,distance=..128,tag=!AM.IsBoss]`
> _asphodel-meadows-v2-1\data\asphodel\functions\accessories\axe\loop.mcfunction_
> `execute as @e[sort=nearest,limit=1,distance=..10,tag=!am_Checked,type=item,nbt={Item:{id:"minecraft:oak_log"}}]` etc.
> _asphodel-meadows-v2-1\data\asphodel\functions\global_tick.mcfunction_
> `execute as @e[type=experience_bottle,tag=!am_Checked] at @s run function asphodel:essence/check`
> `execute as @e[type=firework_rocket,tag=!am_Checked] run function asphodel:custom_blocks/block_check`
> `execute as @e[type=item,tag=!am_Checked] run function asphodel:check_item`
> _asphodel-meadows-v2-1\data\asphodel\functions\accessories\axe\main.mcfunction_
> `execute as @e[sort=nearest,limit=1,distance=..10,tag=!am_Checked,type=item,nbt={Item:{id:"minecraft:oak_log"}}]` etc.
> _asphodel-meadows-v2-1\data\asphodel\functions\custom_portal\portal.mcfunction_
> `as @e[type=#asphodel:can_tp,tag=!p1_teleported]`
> _asphodel-meadows-v2-1\data\asphodel\functions\accessories\magic_mirror\repair.mcfunction_
> `tag @e[type=item,limit=1,sort=nearest,nbt={Item:{id:"minecraft:diamond"}}]`
> **You shouldn't include entities (except for players) with global.ignore tag in any selector**
> **All /title commands show text to players with global.ignore.gui tag, they should not**
> _asphodel-meadows-v2-1\data\asphodel\functions\accessories\hoarding_amulet\drop_items.mcfunction_
> `kill @e[type=item,nbt={Item:{id:"minecraft:barrier"}}]`
> _asphodel-meadows-v2-1\data\asphodel\functions\custom_blocks\infernal_machine\drop.mcfunction_
> `kill @e[distance=..1,type=minecraft:item,nbt={Item:{id:"minecraft:trapped_chest"}}]`
> _asphodel-meadows-v2-1\data\asphodel\functions\custom_blocks\onyx\drop_vase.mcfunction_
> `kill @e[distance=..1,type=minecraft:item,nbt={Item:{id:"minecraft:trapped_chest"}}]`
> **You must not kill entities with global.ignore or global.ignore.kill tag.**
> 
> ### Namespace Convention
> **All the tags must have the namespace. All.**
> Also, /trigger scores are allowed not to have the namespace
> 
> ### Custom Model ID Convention
> **Your Custom Model ID results 113, while the datapack uses 11XXXX and 141XXXX Custom Model Data formats.**
> You should only use 113+4 numbers for your Custom Model Data tags.
> You can only own one ID.
> 
> ## Fix the next things if you also want the Stamp of Quality
> ### Datapack Advancement Convention
> _asphodel-meadows-v2-1\data\global\advancements\asphodel\asphodel.json_ should not be there.
> quoting conventions:
> 
> > as long as you don't pollute /data/global/advancements/folder
> 
> Reply here when you update the datapack and fix everything.

Changes made! please let me know once you review again :)

**Comment by ghost** [comment]
@AidenGyory 

**✔️Certified Datapack
✔️Stamp of Quality**
You can now use [this](https://i.imgur.com/ltLPoQp.png) banner within the Datapack description/wiki/page

Also, great datapack! :)
I like it.
I see you fixed everything at once, and it's very rare for big datapacks like your.
