### ISSUE TITLE
Better Fire

### ISSUE THREAD

**Issue by TheSaltyPug** [mc-datapacks/review-tracker#39]
Project Page: https://github.com/TheSaltyPug/BetterFire/releases

A really simple datapack that creates fire at the place where a fire arrow lands.

- Follows global ignoring convention
- optimized for server performance (scheduling every 5 ticks instead of running every tick)
- no uninstall function, because no scores

**Comment by ghost** [comment]
✔️Certified Datapack
✔️Stamp of Quality

Suggestions:
The datapack is really small, but I think there still is something to fix. Instead of a /setblock, use /fill so you can only replace air or specific blocks like grass etc.
