### ISSUE TITLE
Review for Safe Leashes

### ISSUE THREAD

**Issue by Cray-On** [mc-datapacks/review-tracker#43]
"Animals do not accumulate fall damage potential anymore"
Aiming to counter the bug where mob hanging from leashes accumulate "FallDistance" data.

File : [safe_leashes v1.0.1.zip](https://github.com/mc-datapacks/review-tracker/files/5824632/safe_leashes.v1.0.1.zip)

Official Project Page : https://www.planetminecraft.com/data-pack/safe-leashes/
I'm waiting for the datapack to be reviewed to update it.

**Comment by ghost** [comment]
### ❌Certified Datapack
**Global Ignore Tag Convention**
`execute as @e[nbt={Leash:{},OnGround:0b},tag=!sfl_Hanging] store result score @s sfl_FallDistance run data get entity @s FallDistance 1` includes entities with global.ignore tag modifying its scores then tags and nbt (considering the following commands)
Add tag=!global.ignore in the first selector

You can skip after this.

❌**Stamp of Quality**
Didn't apply the [Datapack Advancement Convention](https://mc-datapacks.github.io/en/conventions/datapack_advancement.html).

**Comment by Cray-On** [comment]
[safe_leashes v1.0.1.zip](https://github.com/mc-datapacks/review-tracker/files/5829945/safe_leashes.v1.0.1.zip)
Fixed !

**Comment by ghost** [comment]
**Safe Leashes by Cray-On**
✅Certified Datapack
✅Stamp of Quality

You can now use [this banner](https://i.imgur.com/ltLPoQp.png) in the datapack web pages.
