### ISSUE TITLE
Review for Nether Start

### ISSUE THREAD

**Issue by Cray-On** [mc-datapacks/review-tracker#44]
"The world spawn is now in the Nether !"
Does pretty much what it says.

File : [nether_start v1.1.1.zip](https://github.com/mc-datapacks/review-tracker/files/5830993/nether_start.v1.1.1.zip)

Official Project Page : https://www.planetminecraft.com/data-pack/nether-start-4786403/
I'm waiting for the datapack to be reviewed to update it.

**Comment by ghost** [comment]
✔️Certified Datapack
✔️"Stamp of Quality"

You can now use [THIS](https://i.imgur.com/ltLPoQp.png) banner in the datapack description/wiki/page etc.
