### ISSUE TITLE
Death Control v1.2.0

### ISSUE THREAD

**Issue by Armoured-Monkey** [mc-datapacks/review-tracker#45]
Project Page: https://www.planetminecraft.com/data-pack/death-control/

I wasn't expecting to add these features so soon. So, sorry about that.

Files that have seen changes/New files: 
deathcontrol/advancements/deathcontrol.json - Changed description to JSON Text Component, so shouldn't be any issues
deathcontrol/functions/config/disable_loot.mcfunction - Works in the same way as pre-existing 'disable' configs
deathcontrol/functions/config/enable_loot.mcfunction - Works in the same way as pre-existing 'enable' configs
deathcontrol/functions/<ALL>
deathcontrol/loot_tables/death.json

**Comment by EstEarth202** [comment]
- Certified Compatibility ✔
- Stamp of Quality 💕
- useful pack 

### Tecnical advice

**Did you know**: `fake_player` doesn't need to use namespace because it is already inside the objective namespace. `dc.keepinv dc_config`
