### ISSUE TITLE
Shamanism Review

### ISSUE THREAD

**Issue by Sipilus** [mc-datapacks/review-tracker#49]
Project Page: https://www.planetminecraft.com/data-pack/shamanism/

**Comment by ghost** [comment]
❌Certified Datapack
❌Stamp of Quality

Why didn't you pass the review? Sure the datapack is fantastic, but the review only depends on conventions.

## Global Ignoring Tag Convention
- **`global.ignore` tag RULE DOES NOT APPLY anymore on player-only selectors**, like `@a` and `@p`. Also. `global.ignore.gui` tag does not apply for `/tellraw`, `/particle` and `/playsound`.
- **you MUST NOT kill entities with `global.ignore.kill`** tag (except if it is a known entity with specific custom tag or nbt). You confused `global.ignore.kill` with `global.ignore.gui` tag. They are two different things, `global.ignore.gui` is for players.

Now let's talk about Tier 2 and 1 conventions, you need to follow some of them if you want to get the Stamp of Quality you deserve.
### Ctc (Common Traits Convention, not needed for the stamp of quality but I suggest to follow it)
- Rules changed, and now **item ctc traits are not anymore** written as strings **in a list**. https://mc-datapacks.github.io/en/conventions/common_trait.html
### Uninstall Function
- **You just do not have it.** Check the conventions.


Check [here](https://mc-datapacks.github.io/en/conventions/index.html) for the current conventions.

Suggestions:
- When summoning fireballs, you should set the Motion and Power nbt tags, not "power" and "motion".
- Too many @e selectors, find a way to reduce them

**Comment by Sipilus** [comment]
I've updated the pack based on the information provided, could you look at it once more?

**Comment by ghost** [comment]
❌Certified Datapack
❌"Stamp of Quality"

Compatibility Issues:
## Global Ignoring Tag
**`global.ignore`** tag RULE **DOES NOT APPLY** anymore on player-only selectors, like `@a` and `@p`. Also. **`global.ignore.gui `** tag does not apply for `/tellraw`, `/particle` and `/playsound.`

Examples:
in _animal_staff_raycast.mcfunction_
❌`particle dolphin ~ ~ ~ 0.1 0.1 0.1 0.1 5 force @a[tag=!global.ignore,tag=!global.ignore.gui,distance=..30]`
✔️`particle dolphin ~ ~ ~ 0.1 0.1 0.1 0.1 5 force @a`
in _everyone.mcfunction_
❌`execute as @s[scores={sip.sp_trance=-1}] run tellraw @s[tag=!global.ignore.gui] "Your trance fades..."`
✔️`execute as @s[scores={sip.sp_trance=-1}] run tellraw @s "Your trance fades..."`
☑️`tellraw @s[scores={sip.sp_trance=-1}] "Your trance fades..."`

## Removing Shared Scoreboard in uninstall.mcfunction
Even if the uninstall function is not Tier 3, it can be a compatibility problem as in this case.
You **MUST NOT remove scoreboards used also by other datapacks**, or you could break them if they are in the world.
This case I see `scoreboard objectives remove ulg_gen`, this is a scoreboard I use in all my datapacks and it is in yours cause used in some places when I rewrited your pack once.
If you use scoreboards used by datapack libraries, remember you must not remove them in the uninstall function.

**Comment by Sipilus** [comment]
All issues should be fixed now!

**Comment by ghost** [comment]
Also if reading `@a[ ]` in the load function made me cry,
### Congratulations!
🐺 Shamanism by @Sipilus is now certified!
**✔️Certified Datapack
✔️Stamp of Quality**

🎉 You are now Certified Datapacker on the discord server.
You can now use [THIS](https://imgur.com/ltLPoQp) banner in the Shamanism datapack description/wiki/banner/posts/web pages.

Remember that someone may choose to review your datapack again in the future and it may not follow conventions anymore. In that case both the role and the banner will be removed...
😆 So keep following conventions!!!
