### ISSUE TITLE
Banners on beds

### ISSUE THREAD

**Issue by Aeldrion** [mc-datapacks/review-tracker#52]
Project Page: https://www.planetminecraft.com/data-pack/banners-on-beds

The data pack provides, with the use of a resource pack, a way for players to apply banner patterns on beds, using [block traversal raycasting](https://github.com/Aeldrion/Iris) and a lot of other annoying things. It complies with all official conventions and style guidelines that apply, and provides an uninstallation function that will remove banner patterns in unloaded chunks. The data pack works in 1.17 snapshots. It has been tested with all forty banner decorations and with complex banner designs.

Scoreboard objectives, `tag` tags, and command storages are all namespaced either with `iris` or `bob`. The resource pack replaces one vanilla model - that of the leather horse armour item - by adding custom model data overrides, using values all prefixed with `432` in compliance with the custom model ID convention.

**Comment by ghost** [comment]
**Banner on beds** by @Aeldrion
✔️Certified Datapack
✔️Followed Style Guidelines

You can now use [this](https://imgur.com/ltLPoQp) banner on datapack description/page/download page etc. etc.

Congratulations for the certification! 🎉🎉
