### ISSUE TITLE
Review for More Books 0.5 (Working Bookshelves) Datapack

### ISSUE THREAD

**Issue by ghost** [mc-datapacks/review-tracker#53]
Project Page: https://www.planetminecraft.com/data-pack/more-books/

2 Things:
-The needed resource pack contains also resources for other datapacks
-The 2 scores are used by other datapacks so the pack does not need an uninstall function

**Comment by EstEarth202** [comment]
# Certified Compatibility ✔️
# Style Guideline Followed 💕
# Final comment:  Cool, useful pack, it should have a function like this in Minecraft vanilla. LMAO Datapack reviewer @EstEarth202. :thumbsup:
