### ISSUE TITLE
GGPI review

### ISSUE THREAD

**Issue by geegaz** [mc-datapacks/review-tracker#54]
Project Page: https://www.planetminecraft.com/data-pack/ggpi-props-interaction/

**A tool for mapmaking.**
Armor Stands created by the datapack use the global.ignore convention, while the datapack only targets its own armor stands (using the namespace `ggpi`)
Since the goal of the datapack is to place entities for maps, uninstalling the datapack will keep the already placed props but delete every hidden ones and remove objectives.

Default prop pack for testing: https://www.planetminecraft.com/data-pack/default-props-ggpi-prop-pack/

**Comment by ghost** [comment]
https://www.planetminecraft.com/data-pack/ggpi-props-interaction/
✔️Certified Compatibility 
✔️Stamp of Quality
However, prop placer and eraser should have traits:{} tag. I'd just place traits:{"item":1b}

https://www.planetminecraft.com/data-pack/default-props-ggpi-prop-pack/
✔️Certified Compatibility 
✔️Stamp of Quality
I'd place "item":1b in traits, also here.

You can now use [this banner](https://imgur.com/ltLPoQp) in the datapacks wiki/webpage.

Sorry for the delay
