### ISSUE TITLE
Item Infos and Food Infos

### ISSUE THREAD

**Issue by SmoochyPit** [mc-datapacks/review-tracker#55]
Project Page: https://github.com/SmoochyPit/Item-Infos/tree/review and https://github.com/SmoochyPit/Food-Infos/tree/review

These two data packs go hand-in-hand, but I decided to separate them so they can be installed independently if the user decides to do so. Let me know if I need to separate this into two issues and I will do so.

Both data packs have a compiled, usable data pack in /out/[name].zip, but I imagine it's probably easier to take a look at the source code.

**Comment by ghost** [comment]
Both:
✔️Certified Compatibility
✔️Followed Style Guideline

I have to say, very original idea.

You can now use [this banner](https://imgur.com/ltLPoQp) for both packs.
