### ISSUE TITLE
Certification Review Request for New in Town by kanokarob

### ISSUE THREAD

**Issue by kanokarob** [mc-datapacks/review-tracker#6]
Project Page: https://www.planetminecraft.com/data-pack/new-in-town-a-settler-s-experience-data-pack/

**Comment by EstEarth202** [comment]
New in Town by @kanokarob 

- [Certified Compatibility :x: ] 
- [Stamp of Quality :two_hearts: ] 

### Namespace

> tag target, id_match, invasionAppear, kingdomInvader, eastSite, westSite, northSite, southSite

### Global ignore
**kill**

```
nitk:siteplanner/build_endportal -> kill @e[tag=!nitCitizen,distance=..3] miss !global.ignore+!kill
nitref:siteplanner_kill -> kill @e[type=item,distance=..1,nbt={Item:{id:"minecraft:dropper"}}] miss !global.ignore+!kill
nitref:siteplanner/finish_portal -> kill @e[tag=!nitCitizen,distance=..2,tag=!global.ignore] miss !kill
```

**pos**
> just add !global.ignore.pos at tp @s 
> nitk:contract & nitco:contract

### Some problems found
> ```
> summon minecraft:area_effect_cloud ~ ~ ~ {Tags:[nitBoxMarker,global.ignore]
> tag @e[tag=nitBoxMarker] add global.ignore
> ```
> Why are you add global.ignore repeated?

> Some `Attributes:[{Name:generic` it's still an old one that isn't version 1.16.

**Comment by kanokarob** [comment]
Changelog for consideration:

Namespace has been utilized for the following tags
```id_match, invasionAppear, kingdomInvader, eastSite, westSite, northSite, southSite```
(target was never used and existed solely in a reference file that was never called. File `nitk:debug/uuid_test` has been removed for clarity)


!global.ignore.kill added to the following
```
nitk:siteplanner/build_endportal -> kill @e[tag=!nitCitizen,distance=..3]
nitref:siteplanner_kill -> kill @e[type=item,distance=..1,nbt={Item:{id:"minecraft:dropper"}}]
nitref:siteplanner/finish_portal -> kill @e[tag=!nitCitizen,distance=..2,tag=!global.ignore]
```
!global.ignore + pos added to the following
```
nitk:contract -> tp @s ~ ~2 ~
nitco:contract -> tp @s ~ ~1 ~
```
Extraneous addition of global.ignore tag removed from the following
```nitco:special/paradox_box/boxinit```

Updated attribute names for all Wither appearances

For reviewer's information: Small addition has been made, but shouldn't affect convention review process.
New Files:
```nitk:siteplanner/build_butcher```
New lines added to files:
```nitk:siteplanner/siteplanner/craft -> ###Crafts a butchery###```

New file has been sent to reviewer via Discord for review.

**Comment by EstEarth202** [comment]
New in Town by @kanokarob 

- [Stamp of Quality :two_hearts: ]

**Comment by EstEarth202** [comment]
New in Town by @kanokarob 

- [Stamp of Quality :two_hearts: ]
