### ISSUE TITLE
Resource Pack Credits datapack

### ISSUE THREAD

**Issue by iijj22gg** [mc-datapacks/review-tracker#67]
Project Page: [https://github.com/IIJJ22GG/resource-pack-credits-datapack](https://github.com/IIJJ22GG/resource-pack-credits-datapack)

**Comment by EstEarth202** [comment]
# Certified Compatibility ✔️
# Style Guideline 💕
You can now use the certified banner for this datapack. The link to your datapack will also be posted on the #certified-datapacks channel.

Final comment: Oh yes, in the Style Guideline, we only have datapack advancement credit, so I can understand why.
