### ISSUE TITLE
Review Request: The Creeper's Code V0.3.2

### ISSUE THREAD

**Issue by CreeperMagnet** [mc-datapacks/review-tracker#8]
[Project link](https://thecreeperscode.com/download)

Changelog
There's been a ton of changes since the last certification, the main thing being reduction of @e (yay, less checking for you) and the removal of global.ignore from all the needed player selectors. Also, added a couple features. 

Honestly, I'd recommend just re-checking it all, due to the major changes in convention over the past few weeks and major optimizations done to the pack.

**Comment by EstEarth202** [comment]
- Certified Compatibility:heavy_check_mark:
- Stamp of Quality :two_hearts: (Re-certification for Quality Datapacker role.)
